# -*- coding: utf-8 -*-
"""
Created on Wed Dec 21 16:22:22 2022

@author: PGS2KOR
"""
BATTERY_PARAM_THD = {
    'Temperature':{
        'LOW_BREACH': 0,
        'HIGH_BREACH': 45,
        'WARNING_TOLERANCE':5
        },
    'SOC':{
        'LOW_BREACH': 20,
        'HIGH_BREACH': 80,
        'WARNING_TOLERANCE':5
        },
    'CHARGE_RATE':{
        'HIGH_BREACH': 0.8,
        'WARNING_TOLERANCE':5
        },
    }

MINIMUM_THRESHOLD_FOR_TEMPERATURE = BATTERY_PARAM_THD['Temperature']['LOW_BREACH']
MAXIMUM_THRESHOLD_FOR_TEMPERATURE = BATTERY_PARAM_THD['Temperature']['HIGH_BREACH']
WARN_TOL_FOR_TEMP = BATTERY_PARAM_THD['Temperature']['WARNING_TOLERANCE']

MINIMUM_THRESHOLD_FOR_SOC = BATTERY_PARAM_THD['SOC']['LOW_BREACH']
MAXIMUM_THRESHOLD_FOR_SOC = BATTERY_PARAM_THD['SOC']['HIGH_BREACH']
WARN_TOL_FOR_SOC = BATTERY_PARAM_THD['SOC']['WARNING_TOLERANCE']

MAXIMUM_THRESHOLD_FOR_CR = BATTERY_PARAM_THD['CHARGE_RATE']['HIGH_BREACH']
WARN_TOL_FOR_CR = BATTERY_PARAM_THD['CHARGE_RATE']['WARNING_TOLERANCE']

